const Result = require("../models/Result");
const Exam = require("../models/Exam");
const User = require("../models/User");

// CREATE / UPDATE RESULT (TEACHER)
const enterMarks = async (req, res) => {
  try {
    const { examId, studentId, marksObtained } = req.body;

    const exam = await Exam.findById(examId);
    if (!exam) {
      return res.status(404).json({ message: "Exam not found" });
    }

    const status =
      marksObtained >= exam.totalMarks * 0.35 ? "Pass" : "Fail";

    const result = await Result.findOneAndUpdate(
      { examId, studentId },
      { marksObtained, status },
      { upsert: true, new: true }
    );

    res.json(result);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};
// GET RESULTS FOR LOGGED-IN STUDENT
const getStudentResults = async (req, res) => {
  try {
    const results = await Result.find({
      studentId: req.user._id,
    })
      .populate({
        path: "examId",
        populate: { path: "classId" },
      });

    const formatted = formatResults(results);
    res.json(formatted);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// GET RESULTS FOR SPECIFIC STUDENT (PARENT VIEW)
const getResultsByStudentId = async (req, res) => {
  try {
    const { studentId } = req.params;
    const results = await Result.find({
      studentId: studentId,
    })
      .populate({
        path: "examId",
        populate: { path: "classId" },
      });

    const formatted = formatResults(results);
    res.json(formatted);
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// Helper for formatting
const formatResults = (results) => {
  return results.map((r) => {
    const percentage = (r.marksObtained / r.examId.totalMarks) * 100;

    let grade = "F";
    if (percentage >= 90) grade = "A+";
    else if (percentage >= 80) grade = "A";
    else if (percentage >= 70) grade = "B";
    else if (percentage >= 60) grade = "C";
    else if (percentage >= 50) grade = "D";

    return {
      examName: r.examId.name,
      subject: r.examId.subject,
      totalMarks: r.examId.totalMarks,
      marksObtained: r.marksObtained,
      percentage: percentage.toFixed(2),
      grade: grade,
      status: r.status,
    };
  });
}

const PDFDocument = require("pdfkit");
const path = require("path");

// GENERATE REPORT CARD PDF
const generateReportCard = async (req, res) => {
  try {
    const { studentId } = req.params;
    const student = await User.findById(studentId).populate("classId");
    if (!student) return res.status(404).json({ message: "Student not found" });

    const results = await Result.find({ studentId }).populate("examId");

    const doc = new PDFDocument({ margin: 50 });
    const safeName = student.name.replace(/\s+/g, "_");

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader("Content-Disposition", `inline; filename="ReportCard_${safeName}.pdf"`);

    doc.pipe(res);

    // Header
    doc.fontSize(20).text("ESchool Academy", { align: "center" });
    doc.fontSize(14).text("Official Report Card", { align: "center" });
    doc.moveDown();

    // Student Details
    doc.fontSize(12).text(`Name: ${student.name}`);
    doc.text(`Class: ${student.classId?.name || "N/A"} - ${student.classId?.section || "N/A"}`);
    doc.text(`Roll Number: ${student.rollNumber || "N/A"}`);
    doc.moveDown();

    // Table Header
    const tableTop = doc.y;
    doc.font("Helvetica-Bold");
    doc.text("Subject", 50, tableTop);
    doc.text("Exam", 200, tableTop);
    doc.text("Marks", 350, tableTop);
    doc.text("Grade", 450, tableTop);
    doc.font("Helvetica");
    doc.moveDown();

    // Table Rows
    let y = doc.y;
    results.forEach(r => {
      if (!r.examId) return;
      const percentage = (r.marksObtained / r.examId.totalMarks) * 100;
      let grade = "F";
      if (percentage >= 90) grade = "A+";
      else if (percentage >= 80) grade = "A";
      else if (percentage >= 70) grade = "B";
      else if (percentage >= 60) grade = "C";
      else if (percentage >= 50) grade = "D";

      doc.text(r.examId.subject, 50, y);
      doc.text(r.examId.name, 200, y);
      doc.text(`${r.marksObtained} / ${r.examId.totalMarks}`, 350, y);
      doc.text(grade, 450, y);
      y += 20;
    });

    // Footer
    doc.moveDown(4);
    doc.fontSize(10).text("Generated by ESchool ERP System", { align: "center" });

    doc.end();

  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

module.exports = { enterMarks, getStudentResults, getResultsByStudentId, generateReportCard };
